Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using QueueControlServer.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;



namespace QueueControlServer.Controllers
{
    
    
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
      [Authorize(Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        public IActionResult Index()
        { 
            if (HttpContext.User.IsInRole("Supervisor"))
            {
                return Redirect("/Home/IndexSupervizor");
            }
            if (HttpContext.User.IsInRole("Terminal"))
            {
                return View();
            }
            if (HttpContext.User.IsInRole("admin"))
            {
                return Redirect("/Home/IndexSupervizor");
            }

                return View();
        }

        [Authorize(Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        public IActionResult IndexSupervizor()
        {
            return View();
        }


        public IActionResult IndexAdministration()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OrganizationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using QueueControlServer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QueueControlServer.Controllers
{
    [Authorize(AuthenticationSchemes = MVCJwtTokens.AuthSchemes, Roles = "admin,Terminal,Supervisor,LocalAdmin")]
    public class OrganizationsController : Controller
    {

        private readonly ApplicationDBContext _context;
        private readonly IHubContext<SignalServer> _signalHub;

        public OrganizationsController(ApplicationDBContext context, IHubContext<SignalServer> signalHub)
        {
            _context = context;
            _signalHub = signalHub;

        }
        /*  public async Task<IActionResult> Index()
          {
              return View(await _context.Factories.ToListAsync());
          } */

        public async Task<IActionResult> Index(string factory, string name)        // HACK временно, переписать метод!!1
        {
            var Factories = await _context.Factories.ToListAsync();
            IQueryable<User> users = _context.Terminals.Include(p => p.Factory);

            if (factory != null)
            {
                users = users.Where(p => p.Id == factory);
            }
            List<Factory> factories = _context.Factories.ToList();

            


            return View(factories);
        }

        [HttpGet]
        public IActionResult GetOrganization(string Factory, string Brand, string Package)
        {
            IQueryable<Factory> Factorys = _context.Factories;

            return Ok(Factorys);
        }

        public IActionResult CreateFactory() => View();

        public IActionResult CreateCarrier() => View();





        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("CreateFactory")]        // url
        public async Task<IActionResult> Create([Bind("OrganizationName, OrganizationId")] Factory factory)
        {

            IQueryable<Factory> Factorys = _context.Factories;
            _context.Add(factory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("CreateCarrier")]
        public async Task<IActionResult> Create([Bind("OrganizationName")] Carrier carrier)  // HACK  перегрузка для добавления предприятия
        {

            IQueryable<Carrier> carriers = _context.Carriers;
            _context.Add(carrier);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

    }
}

Controllers/QueuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QueueControlServer.Interfaces;
using QueueControlServer.Models;
using QueueControlServer.Services;
using QueueControlServer.ViewModels.Queue;
using QueueControlServer.ViewModels.QueuesList;

namespace QueueControlServer.Controllers
{
    [Authorize(AuthenticationSchemes = MVCJwtTokens.AuthSchemes, Roles = "admin,Terminal,Supervisor,LocalAdmin")]
    public class QueuesController : Controller
    {
        private readonly ApplicationDBContext _context;

        public QueuesController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: Queues
        [Authorize(Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Queue.ToListAsync());

        }



        [Authorize(Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        public async Task<IActionResult> QueuesList([FromServices] IGetUserClaim UserClaimService)
        {
            UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity);
            var gg = UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity);
            var yy = UserClaimService.GetUserRole((ClaimsIdentity)User.Identity);
            if (UserClaimService.GetUserRole((ClaimsIdentity)User.Identity) == "admin")
            {
                var tempView = await _context.Queue.ToListAsync();
                return View(tempView);
            }
            else
            {
                var tempView = await _context.Queue.Where(p => p.Factory.OrganizationName == UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity)).ToListAsync();
                return View(tempView);
            }


            // return View(tempView);
        }




        [Authorize(AuthenticationSchemes = MVCJwtTokens.AuthSchemes, Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        public async Task<IActionResult> QueuesPackages([FromServices] IGetUserClaim UserClaimService)  // Выборка Упаковок
        {
            UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity);

            var QueuesPackage = new List<Package>();

            if (UserClaimService.GetUserRole((ClaimsIdentity)User.Identity) == "admin")
            {

                var tempView = await _context.Queue.ToListAsync();
                foreach (var p in tempView)
                {
                    _context.Queue.Include(u => u.Package).Include(u => u.Package);
                    QueuesPackage.Add(p.Package);
                }
                return View(QueuesPackage.Distinct());
            }
            else
            {

                var tempView = await _context.Queue.Where(p => p.Factory.OrganizationName == UserClaimService
                .GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity)).Include(u => u.Package).ToListAsync();

                if (UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity) != null)
                {
                   // tempView = (List<Queue>)tempView.Where(p => p.Factory.OrganizationName == UserClaimService
                   // .GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity));

                    List<Guid> FactoryQ = UserClaimService
                           .GetUserClaim("TerminalQueues", (ClaimsIdentity)User.Identity).Split(",").ToList().ConvertAll(Guid.Parse);

                    tempView = tempView.Where(p => FactoryQ.Contains(p.QueueId)).ToList();
                }


                foreach (var p in tempView)
                {

                    QueuesPackage.Add(p.Package);
                }
                return View(QueuesPackage.Distinct());
            }

        }

        [Authorize(AuthenticationSchemes = MVCJwtTokens.AuthSchemes, Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        public async Task<IActionResult> QueuesBrands([FromServices] IGetUserClaim UserClaimService, string PackageName)
        {

            if (UserClaimService.GetUserRole((ClaimsIdentity)User.Identity) == "admin")
            {
                return View();
            }
            else
            {
                var tempView = await _context.Queue.Where(p => p.Factory.OrganizationName == UserClaimService
                .GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity) & p.Package.PackageName == PackageName).Include(u => u.Brand).ToListAsync();
               
                if (UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity) != null)
                {
                    // tempView = (List<Queue>)tempView.Where(p => p.Factory.OrganizationName == UserClaimService
                    // .GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity));

                    List<Guid> FactoryQ = UserClaimService
                           .GetUserClaim("TerminalQueues", (ClaimsIdentity)User.Identity).Split(",").ToList().ConvertAll(Guid.Parse);

                    tempView = tempView.Where(p => FactoryQ.Contains(p.QueueId)).ToList();
                }
                return View(tempView);
            }
        }


        [Authorize(AuthenticationSchemes = MVCJwtTokens.AuthSchemes, Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        [HttpPost]
        public IActionResult GetQueue([FromServices] IGetUserClaim UserClaimService, string Factory, string FactoryName)
        {

            IQueryable<Queue> queues = _context.Queue;
            //.Where(p => p.Factory.OrganizationName== UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity));  // Undone дорисовать фильтор для своих очередей 
            if (UserClaimService.GetUserRole((ClaimsIdentity)User.Identity) == "admin")
            {

            }
            else if (UserClaimService.GetUserRole((ClaimsIdentity)User.Identity) == "Supervisor")
            {
                if (UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity)!=null)
                {
                    queues = queues.Where(p => p.Factory.OrganizationName == UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity));
                }
                else if (UserClaimService.GetUserClaim("CarrierName", (ClaimsIdentity)User.Identity) != null)
                {
                   var itemCarries = _context.QueueItems.Where(p => p.CarrierName == UserClaimService.GetUserClaim("CarrierName", (ClaimsIdentity)User.Identity));

                    List<Guid> CarriesQ = new List<Guid>();
                   foreach (var item in itemCarries)
                    {
                        CarriesQ.Add(item.QueueId);
                    }
                  queues=queues.Where(p=> CarriesQ.Contains(p.QueueId));

                }



            }
            else
            {
                queues = queues.Where(p => p.Factory.OrganizationName == UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity));

            }  // Undone дорисовать фильтор для своих очередей 





            if (FactoryName != null && FactoryName != "Все")
            {
                queues = queues.Where(p => p.Factory.OrganizationName == FactoryName);
            }

           /* else
            {
                queues = queues.Where(p => p.Factory.OrganizationName == FactoryName);   // HACK пока лищённое смысла условие, дописать

            }*/

            _context.Queue.Include(p => p.Factory.OrganizationName);

            var tempqueues = queues.ToList();
          //  tempqueues.Insert(0, new Queue { QueueName = "Все", QueueId = Guid.Empty });

            QueuesList viewModel = null; // new QueuesList
            /* {
                 Queue = tempqueues,
                 //  Queue.Insert(0, new Queue { QueueId = 0, QueueName = "Все" });

                 //   Factories =  new SelectList (factorry, "OrganizationName", "OrganizationId"),

             };*/


            //return Ok(viewModel);

            return Json(tempqueues);
        }




        // GET: Queues/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var queue = await _context.Queue
                .FirstOrDefaultAsync(m => m.QueueId == id);
            if (queue == null)
            {
                return NotFound();
            }

            return View(queue);
        }

        // GET: Queues/Create
        public IActionResult Create()
        {
            IEnumerable<Factory> factories = _context.Factories.ToList();
            ViewBag.Factory = new SelectList(factories, "OrganizationId", "OrganizationName");

            IEnumerable<Brand> brands = _context.Brands.ToList();
            ViewBag.Brand = new SelectList(brands, "GoodsParameterId", "BrandName");

            IEnumerable<Package> packages = _context.Packages.ToList();
            ViewBag.Package = new SelectList(packages, "GoodsParameterId", "PackageName");
            return View();
        }

        // POST: Queues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateQueueViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Factory = _context.Factories.Find(model.OrganizationId);
                model.Brand = _context.Brands.Find(model.GoodsParameterId);
                model.Package = _context.Packages.Find(model.PackageParameterId);

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout.cshtml";
}

<div class="text-center">
    @* <h1 class="display-4">Хрен ДЕрьмо и Помидоры</h1>*@
    @* <p>Learn about <a href="https://stc93.com/"> Южная Транспортная компания</a>.</p>*@

</div>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <title>Grid Layout в CSS3</title>
    <style>

        .grid-container {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            grid-template-rows: repeat(1, 1fr);
            max-height: 100%;
        }

        .grid-item {
            font-size: 180%;
            padding: 0.5em;
            color: white;
            max-height: 100%;
            max-width: 100%
        }

        .color1 {
            background-color: #ffffff;
        }

        .color2 {
            background-color: #9BC850;
        }

        .color3 {
            background-color: #f7b2b2;
        }

        .color4 {
            background-color: #2A9FBC;
        }

        .color5 {
            background-color: #4e342e;
        }

        .btn-block {
            padding: 50% 0;
            /* define values in pixels / Percentage or em. whatever suits
                                                your requirements  Здесь центровка  */
        }

        body {
            background-color: white;
            background-image: url("../images/Photo1.jpg");
            background-size: cover;
            background-repeat: no-repeat;
        }

        Layout {
            width: 100%;
        }
    </style>
</head>

<body>
    <div class="container-fluid">
        <div class="row justify-content-md-center">
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row justify-content-md-center">
            @* <a type="button" class="btn btn-outline-primary  Layout container-fluid " asp-controller="Queues" asp-action="QueuesList"><h1><font size="11">Просмотр очередей</font></h1></a>  // старый просмотр*@


            @if (User.IsInRole("admin"))
            {
                <a type="button" class="btn btn-outline-primary  Layout container-fluid " asp-controller="QueueItems" asp-action="Index"><h1><font size="11">Просмотр очередей</font></h1></a>
            }
            else
            {
                <a type="button" class="btn btn-outline-primary  Layout container-fluid " asp-controller="Queues" asp-action="QueuesPackages"><h1><font size="11">Просмотр очередей</font></h1></a>
            }
            @if (User.Identity.IsAuthenticated)
            {

            }
            else
            {
                <a type="button" class="btn btn-outline-danger  container-fluid" asp-controller="Account" asp-action="Login">Вход</a>
                @*<a asp-controller="Account" asp-action="Register">Регистрация</a>*@
            }

            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
            <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
        </div>
    </div>


    <div class="grid-container">

        <div class="grid-item ">
            <a class="btn btn-outline-success btn-block" asp-controller="QueueItems" asp-action="Create"><h1><font size="9">Регистрация на погрузку</font></h1></a>
            @*  <button type="button" class="btn btn-success btn-lg btn-block" py-4>Block level button</button>*@
        </div>

        <div class="grid-item ">

            <a class="btn btn-outline-danger btn-block" asp-controller="QueueItems" asp-action="DeleteRequest"><h1><font size="9">Отменить регистрацию</font></h1></a>

        </div>
    </div>
</body>

@*
    Форма регистрации:
*@
@{
    ViewData["Title"] = "Home Page";
}

@*<body>

    @if (User.IsInRole("user"))
    {
    <p>@User.Identity.Name</p>

    <form method="post" asp-controller="Account" asp-action="Logout">
    <input type="submit" value="Выход" />
    </form>
    <p>
    <a asp-controller="QueueItems" asp-action="Create">Регистрация в очереди</a>
    </p>
    }
    else
    {
    <a asp-controller="Account" asp-action="Login">Вход</a>
    <a asp-controller="Account" asp-action="Register">Регистрация</a>
    }
    </body>*@

Views/Home/IndexAdministration.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_LayoutVisors.cshtml";
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/microsoft/signalr/dist/browser/signalr.js"></script>
@* <script src="~/js/site.js"></script>*@
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<div class="container">
    <table class="table">
        
        <tr>
            <td>
                 <a class="navbar-brand" asp-area="" asp-controller="Organizations" asp-action="Index">
                <h1>Организации</h1>
            </a>
            </td>
           
        </tr>
        <tr>
            <td>
            <a class="navbar-brand" asp-area="" asp-controller="users" asp-action="Index">
                <h1>Пользователи</h1>
            </a>
            </td>
        </tr>
        <tr>
            <td>
            <a class="navbar-brand" asp-area="" asp-controller="goodsparameters" asp-action="Index">
                <h1>Параметры очередей</h1>
            </a>
            </td>
            <td>
               <h1>/</h1> 
            </td>
            <td>
            <a class="navbar-brand" asp-area="" asp-controller="Queues" asp-action="Index">
                <h1>Очереди</h1>
            </a>
            </td>
        </tr>
        <tr>
            <td>
            <a class="navbar-brand" asp-area="" asp-controller="roles" asp-action="Index">
                <h1>Роли</h1>
            </a>
            </td>
        </tr>




    </table>
</div>

Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QueueControlServer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link rel="stylesheet" href="~/lib/jquery/dist/jquery.js" *@
    


</head>
<body>
    <header>
   
    </header>
    <div class="container" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - QueueControlServer @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
       @*<script src="~/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>