ViewModels/QueueItems/CreateWithoutBarecodeViewModel.cs
using QueueControlServer.Models;

namespace QueueControlServer.ViewModels.QueueItems
{
    public class CreateWithoutBarecodeViewModel
    {
        public int QueueItemId { get; set; }               // ид элемента
        public int OderLine { get; set; }              // место в очереди (поля имеют нулевые значение в базе, но заполняються в мщмент вызова метода GetQueueItems в зависимости от входных данных метода )
        public string CarNumber { get; set; }          // гос номер ТС
        public string Barecode { get; set; }           // Штрихкод карты, если карта не использовалась, будет нулевым
        public string DriverName { get; set; }         // ФИО Водителя


        public string GoodsParameterId { get; set; }
        public string BrandName { get; set; }              // марка цемента (значение запрашиваеться из стороннего сервиса или вводиться пользователем )
        public Brand Brand { get; set; }                 // марка цемента (значение из параметров целевого завода)


        public string PackageName { get; set; }            // Вид упаковки  (значение запрашиваеться из стороннего сервиса или вводиться пользователем ) 
        public Package Pacakege { get; set; }             // вид упаковки из целевого завода


        public string QueueName { get; set; }   // имя очереди

       
    }
}

ViewModels/QueueItems/QueueItemsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using QueueControlServer.Models;

namespace QueueControlServer.ViewModels.QueueItems
{
    public class QueueItemsListViewModel
    {
        public IEnumerable<QueueControlServer.Models.QueueItems> QueueItems { get; set; }
        public SelectList Organizations { get; set; }
        public string OrganizationsName { get; set; }
        public SelectList Factories { get; internal set; }
        public SelectList Carriers { get; internal set; }
        public string Name { get; set; }
        public SelectList QueueNames { get; set; }
    }
}

Controllers/QueueItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using QueueControlServer.Models;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using System.Text;
using RestSharp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using System.Web;
using RestSharp.Deserializers;
using Newtonsoft.Json.Linq;
using QueueControlServer.ViewModels;
using QueueControlServer.ViewModels.QueueItems;
using QueueControlServer.Interfaces;
using Microsoft.Extensions.Options;
using QueueControlServer.Data.Services;

namespace QueueControlServer.Controllers
{
    [Authorize(AuthenticationSchemes = MVCJwtTokens.AuthSchemes, Roles = "admin,Terminal,Supervisor,LocalAdmin")]
    public class QueueItemsController : Controller
    {
     

        private readonly ApplicationDBContext _context;
        private readonly IHubContext<SignalServer> _signalHub;
        private readonly IOptions<MyAppSettings> _options;
        // private string UrlDecode;

        public QueueItemsController(ApplicationDBContext context, IHubContext<SignalServer> signalHub, IOptions<MyAppSettings> options)
        {
            _context = context;
            _signalHub = signalHub;
            _options = options;
        }

        // GET: QueueItems
        [Authorize(Roles = "admin,Terminal,Supervisor,LocalAdmin")]

        public async Task<IActionResult> Index()
        {

            List<Factory> factorys = _context.Factories.ToList();
            factorys.Insert(0, new Factory { OrganizationId = new Guid("5b8f190e-d679-498a-8e09-90cafd23683f"), OrganizationName = "Все" });
            List<Carrier> carriers = _context.Carriers.ToList();
            carriers.Insert(0, new Carrier { OrganizationId = new Guid("5b8f190e-d679-498a-8e09-90cafd23683f"), OrganizationName = "Все" });

          ;


            QueueItemsListViewModel viewModel = new QueueItemsListViewModel
            {

                QueueItems = await _context.QueueItems.ToListAsync(),
                Factories = new SelectList(factorys, "OrganizationId", "OrganizationName"),
                Carriers = new SelectList(carriers, "OrganizationId", "OrganizationName")
            };
            return View(viewModel);

        }

        public async Task<IActionResult> QueueItemsList(string QueueName, string Factory)
        {

            List<Factory> factorys = _context.Factories.Where(p => p.OrganizationName == Factory).ToList();
            // factorys.Insert(0, new Factory { OrganizationId = 0, OrganizationName = "Все" });
            List<Carrier> carriers = _context.Carriers.ToList();
            carriers.Insert(0, new Carrier { OrganizationId = new Guid("5b8f190e-d679-498a-8e09-90cafd23683f"), OrganizationName = "Все" });

            List<Queue> queues = _context.Queue.Where(p => p.QueueName == QueueName).ToList();
            //IQueryable<QueueItems> queueItems = _context.QueueItems;

            //  queueItems = queueItems.Where(p => p.Factory.OrganizationName == Factory);


            QueueItemsListViewModel viewModel = new QueueItemsListViewModel
            {
                QueueNames = new SelectList(queues, "QueueId", "QueueName"),
                QueueItems = await _context.QueueItems.ToListAsync(),
                Factories = new SelectList(factorys, "OrganizationId", "OrganizationName"),
                Carriers = new SelectList(carriers, "OrganizationId", "OrganizationName")
            };
            return View(viewModel);

        }

        [HttpGet]

       


       
        [Authorize(AuthenticationSchemes = MVCJwtTokens.AuthSchemes, Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        [HttpPost]
        public IActionResult GetQueueItems([FromServices] IGetUserClaim UserClaimService, string BrandName, string PackageName, string FactoryName, string CarrierName, string Search, string QueueName, List <string> QueueList)   // TODO будем передавать методу параметры и выводить списки в зависимости от их значений. ПЕредаём: 1) роль текущего пользователя, марку цемента, упаковку 
        {

            {                                                              
                string Role = UserClaimService.GetUserRole((ClaimsIdentity)User.Identity);


                //  Определение 
                if (Role != "admin")
                {
                    if (Role != "Carrier")
                    {
                        FactoryName = UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity);
                        //  if (string.IsNullOrEmpty(FactoryName)) ;
                    }
                    if (Role != "Factory")
                    {
                        CarrierName = UserClaimService.GetUserClaim("CarrierName", (ClaimsIdentity)User.Identity);
                    }

                }

                IQueryable<QueueItems> queueItems = _context.QueueItems;
                // Ниже поиск по строке !
                {
                    if (!String.IsNullOrEmpty(Search))
                    {
                        var tempqueueItems = queueItems;
                        tempqueueItems = tempqueueItems.Where((p => p.CarNumber.Contains(Search)));
                        if (tempqueueItems.Count() == 0)
                        {
                            queueItems = queueItems.Where((p => p.DriverName.Contains(Search)));
                        }
                        else
                        {
                            queueItems = tempqueueItems;

                        }
                    }


                }

               /* if (Role != "admin") //   провера на администратора 
                {
                    queueItems = queueItems.Where(p => p.Factory.OrganizationName == FactoryName);
                }*/


                if (FactoryName != null && FactoryName != "Все")
                {
                    queueItems = queueItems.Where(p => p.FactoryName == FactoryName);
                }

                if (CarrierName != null && CarrierName != "Все")
                {
                    queueItems = queueItems.Where(p => p.CarrierName == CarrierName);
                }

               

                if (QueueName != null && QueueName != "Все")
                {
                    queueItems = queueItems.Where(p => p.QueueName == HttpUtility.UrlDecode(QueueName));
                }
               
               
                 if (QueueList.Count != 0)
                {
                    QueueList = JsonConvert.DeserializeObject<List<string>>(QueueList[0]);

                    IEnumerable<QueueItems> tempqueueItems = new List<QueueItems>();

                    foreach (var item in QueueList)
                    {
                        IEnumerable<QueueItems> queueItems1 = new List<QueueItems>();
                        queueItems1 = queueItems.Where(p => p.Queue.QueueId == Guid.Parse(item));
                        tempqueueItems = tempqueueItems.Concat(queueItems1);
                       
                    }
                  
                     queueItems = tempqueueItems.AsQueryable();

                }



                queueItems = from u in queueItems orderby u.OderLine select u;  // сортировка по порядку в очереди

                QueueItemsListViewModel viewModel = new QueueItemsListViewModel
                {
                    QueueItems = queueItems.ToList()

                    //   Factories =  new SelectList (factorry, "OrganizationName", "OrganizationId"),

                };

                return Ok(viewModel);
            }
            


        }



        // GET: QueueItems/Details/5
        public async Task<IActionResult> Details(Guid? QueueItemId)
        {
            if (QueueItemId == null)
            {

                return NotFound();
            }

            var queueItem = await _context.QueueItems
                .FirstOrDefaultAsync(m => m.QueueItemId == QueueItemId);
            if (queueItem == null)
            {
                return NotFound();
            }

            return View(queueItem);
        }

        // GET: QueueItems/Create
        public IActionResult Create()
        {
            // QueueItems c = _context.QueueItems.FirstOrDefault(m => m.Barecode == Barecode);

            return View();
        }
        public IActionResult CreateWithoutBarecode([FromServices] IGetUserClaim UserClaimService)
        {
            IEnumerable<Brand> brands = _context.Brands.ToList();
            ViewBag.Brand = new SelectList(brands, "GoodsParameterId", "BrandName");
            if (UserClaimService.GetUserRole((ClaimsIdentity)User.Identity) == "admin")
            {
                IEnumerable<Queue> queues = _context.Queue.ToList();
                ViewBag.Queue = new SelectList(queues, "QueueId", "QueueName");
            }
            else
            {
                IEnumerable<Queue> queues = _context.Queue.Where(p => p.Factory.OrganizationName == UserClaimService.GetUserClaim("FactoryName", (ClaimsIdentity)User.Identity)).ToList();
                ViewBag.Queue = new SelectList(queues, "QueueId", "QueueName");
            }

            return View();
        }


        [HttpPost]                    
                                       //   [ValidateAntiForgeryToken]
        [Authorize(AuthenticationSchemes = MVCJwtTokens.AuthSchemes, Roles = "admin,Terminal,Supervisor,LocalAdmin")]
        // [Authorize(Roles = "admin,factory")]

        public async Task<IActionResult> Create([Bind("QueueItemsId,OderLine,CarNumber,Barecode,Factory,Brand")][FromServices] IGetUserClaim UserClaimService, QueueItems queueItem)  // стандартная генерация элемента в очереди, подразумевающая получение основных данных с сервера 1С 
        {

Views/QueueItems/Create.cshtml
@model QueueControlServer.Models.QueueItems


@*@using (Html.BeginForm())
    {
    @Html.AntiForgeryToken()
    <div>
    @Html.LabelFor(model => model.Barecode)
    <p>@Html.EditorFor(model => model.Model)</p>
    </div>

    <div>
    @Html.LabelFor(model => model.Year)
    <p>@Html.EditorFor(model => model.Year)</p>
    </div>
    <p><input type="submit" value="Добавить" /></p>
    }
    </div>*@
@{
    ViewData["Title"] = "Create";
    Layout = "_Layout.cshtml";
}



<style type="text/css">
    .demo-row {
        width: 400px;
        margin: 0 auto;
        padding: 15px;
    }

    body {
        background-color: white;
        background-image: url("../images/Photo1.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }

    form-control {
        height: calc(2.25rem + 132px);
        line-height: 3.5;
        font-size: 11rem;
    }

    input[type=password] {
        width: 100%;
        padding: 50px 20px;
        margin: 8px 0;
        box-sizing: border-box;
        border: 2px solid green;
        border-radius: 4px;
        text-align: center;
        font-size: 3.7em;
    }

    input[type=submit] {
        padding: 5px 15px;
        background: #ccc;
        border: 0 none;
        cursor: pointer;
        -webkit-border-radius: 5px;
        border-radius: 5px;
    }

    .modal {
        text-align: center;
    }

        .modal:before {
            display: inline-block;
            vertical-align: middle;
            content: " ";
            height: 100%;
        }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }

    .modal-header {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -webkit-justify-content: space-between;
        -ms-flex-pack: justify;
        justify-content: space-between;
        padding: 5px;
        border-bottom: 1px solid #eceeef;
    }

</style>


<h1>Сканируйте карту водителя:</h1>

<h4></h4>
<hr />

<div class="row">
    <div class="container-fluid">
        <form>
            <div class="form-group container-fluid">
                <div class="container-fluid">
                    <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
                    <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
                    <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>

                    <input asp-for="Barecode" class="form-control container-fluid" oninput="myFunction()" type="password" maxlength="13" id="target" onchange="input.focus" onblur="this.focus() " autofocus />@*фокус поле*@
                    <span asp-validation-for="Barecode" class="text-danger"></span>
                </div>
                <div class="checkout__agree">
                    <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
                <label class="checkbox">
                    <input type="checkbox" id="agreement-10" class="checkbox__control" checked="">
                    <span class="checkbox__label">Сканируя карту, Вы даёте свое согласие на обработку персональных данных, в соответствии с Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных», на условиях и для целей, определенных в <a onclick="ShowAgreement();" href="javascript:void(0);">Согласии на обработку персональных данных</a></span>
                </label>
            </div>
                <script>
                       // Фокусировка ввода
                     function myFunction () {
                     var ff = document.getElementById('target').value;
                     localStorage.setItem('selected', ff);
                    }
                </script>
                <script src="~/lib/jquery/dist/jquery.min.js"></script>
            </div>
            <div class="form-group">
            </div>
        </form>
    </div>


    <script>

           // Создание модального окна.

          //  $(function () {
        //    $('button[data-toggle="ajax-modal"]').click(function (event) {
         //   var url = $(this).data('url');
         //   $.get(url).done(function (data) {
         //   $('#modal-placeholder').html(data);
         //   $('#modal-placeholder > .modal').modal('show');
         //        });
         //     });
         //  });


           // перевесить всё на событие энтер
            $("form").on("submit", function PostBarecode(){
              event.preventDefault();
            //  document.getElementById("CreateButtomSubmit").click();
               var url = "_CreateResultMessegePartial";
            $.get(url).done(function (data) {
            $('#modal-placeholder').html(data);
            $('#modal-placeholder > .modal').modal('show');
             document.getElementById('target').remove();


                 });
                 })

    </script>

    <div id="modal-placeholder"></div>

</div>
<h1></h1>
@if (User.IsInRole("Terminal"))
{
<h1> <font color="red">ВНИМАНИЕ !!! Только если у Вас нет карты водителя: </font> </h1>
<a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
<a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>

<div>
    <a class="btn btn-outline-warning py-5" asp-controller="QueueItems" asp-action="CreateWithoutBarecode"><h1>Регистрация в очереди без карты</h1></a>
</div>
}
<div class="form-group container-fluid">
    <a class="   Layout container-fluid "><h1><font size="9"></font></h1></a>
</div>

@*<!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Launch static backdrop modal
    </button>*@

<!-- Modal -->
@*<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
    <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
    <input asp-for="Barecode" class="form-control"  id="target" maxlength="13" value="@ViewBag.Barecode" readonly />
    <script>



    function GetBarecode()
    {
    var test = localStorage.getItem('selected');
    input = document.getElementById('target');
    target.value = test
    }

    $('#Create').click(function () {
    GetBarecode();
    })
    GetBarecode();




    </script>
    </div>
    <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary">Understood</button>
    </div>
    </div>
    </div>
    </div>*@






@section Scripts {

@*<script type="text/javascript">

    $(function () {
    $.ajaxSetup({ cache: false });
    $("Create").click(function (e) {

    e.preventDefault();
    $.get(this.href, function (data) {
    $('#dialogContent').html(data);
    $('#modDialog').modal('show');
    });
    });
    })
    </script>*@





}

Views/QueueItems/Delete.cshtml
@model QueueControlServer.Models.QueueItems

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QueueItem</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OderLine)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OderLine)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Barecode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Barecode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="QueueItemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/QueueItems/DeleteRequest.cshtml
@model QueueControlServer.Models.QueueItems

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout.cshtml";
}
<style type="text/css">
    .demo-row {
        width: 400px;
        margin: 0 auto;
        padding: 15px;
    }

    body {
        background-color: white;
        background-image: url("../images/Photo1.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }

    form-control {
        height: calc(2.25rem + 132px);
        line-height: 3.5;
        font-size: 11rem;
    }

    input[type=password] {
        width: 100%;
        padding: 50px 20px;
        margin: 8px 0;
        box-sizing: border-box;
        border: 2px solid green;
        border-radius: 4px;
        text-align: center;
        font-size: 3.7em;
    }

    input[type=submit] {
        padding: 5px 15px;
        background: #ccc;
        border: 0 none;
        cursor: pointer;
        -webkit-border-radius: 5px;
        border-radius: 5px;
    }

    .modal {
        text-align: center;
    }

        .modal:before {
            display: inline-block;
            vertical-align: middle;
            content: " ";
            height: 100%;
        }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }

    .modal-header {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -webkit-justify-content: space-between;
        -ms-flex-pack: justify;
        justify-content: space-between;
        padding: 5px;
        border-bottom: 1px solid #eceeef;
    }

</style>


<h1>Для удаление из очереди сканируйте карту водителя</h1>
<h1> <font color="red">ВНИМАНИЕ !!! ПОСЛЕ СКАНА КАРТЫ ВЫ БУДЕТЕ УДАЛЕНЫ ИЗ ОЧЕРЕДИ! </font> </h1>

<h4></h4>
<hr />

<div class="row">
    <div class="container-fluid">
        <form>
            <div class="form-group container-fluid">
                <div class="container-fluid">
                   
                    <input asp-for="Barecode" class="form-control container-fluid" oninput="myFunction()" type="password" maxlength="13" id="target" onchange="input.focus" onblur="this.focus()" autofocus />
                    <span asp-validation-for="Barecode" class="text-danger"></span>
                </div>
                <script>
                    function myFunction () {
                        var ff = document.getElementById('target').value;
                        localStorage.setItem('selected', ff);
                    }
                      //var test = localStorage.getItem('selected');
                </script>
                <script src="~/lib/jquery/dist/jquery.min.js"></script>
            </div>


            <div class="form-group">
                @* <input type="submit" value="Delete" class="btn btn-danger" />*@
            </div>
        </form>
    </div>
    <script>

        $("form").on("submit", function PostBarecode(){
             event.preventDefault();
           //  document.getElementById("CreateButtomSubmit").click();
              var url = "_DeleteResultMessegePartial";
           $.get(url).done(function (data) {
           $('#modal-placeholder').html(data);
           $('#modal-placeholder > .modal').modal('show');
            document.getElementById('target').remove();


                });
                })





    </script>
    <div id="modal-placeholder"></div>

</div>


@*<div>
    <a asp-action="Index">Отмена регистрации</a>
</div>*@

<!-- Button trigger modal -->
@*<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Launch static backdrop modal
</button>*@

<!-- Modal -->
@*<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Understood</button>
            </div>
        </div>
    </div>
</div>*@






@section Scripts {
    {
    @*await Html.RenderPartialAsync("_ValidationScriptsPartial");*@
}
}

Views/QueueItems/Details.cshtml
@model QueueControlServer.Models.QueueItems

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>QueueItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OderLine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OderLine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Barecode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Barecode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.QueueItemId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/QueueItems/Edit.cshtml
@model QueueControlServer.Models.QueueItems

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>QueueItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="QueueItemId" />
            <div class="form-group">
                <label asp-for="OderLine" class="control-label"></label>
                <input asp-for="OderLine" class="form-control" />
                <span asp-validation-for="OderLine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarNumber" class="control-label"></label>
                <input asp-for="CarNumber" class="form-control" />
                <span asp-validation-for="CarNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriverName" class="control-label"></label>
                <input asp-for="DriverName" class="form-control" />
                <span asp-validation-for="DriverName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Barecode" class="control-label"></label>
                <input asp-for="Barecode" class="form-control" />
                <span asp-validation-for="Barecode" class="text-danger"></span>
            </div>
            <div class="form-group">
                 <label asp-for="Factory" class="control-label"></label>
                 <select asp-for="FactoryId" asp-items="ViewBag.Factory"></select>
            </div>
            <div class="form-group">
                 <label asp-for="Queue" class="control-label"></label>
                 <select asp-for="QueueId" asp-items="ViewBag.Queues"></select>
            </div>
            <div class="form-group">
                 <label asp-for="Carriers" class="control-label"></label>
                 <select asp-for="CarrierId" asp-items="ViewBag.Carrier"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}